---
- name: 'Install Utilities'
  tags:
    - 'node'
    - 'update'
  sudo: true
  shell: "npm install -g bower grunt-cli;"

- name: 'Install dependencies'
  tags:
    - 'node'
    - 'bower'
  shell: "cd /vagrant; npm install && bower install"

- name: 'Move Files'
  sudo: true
  shell: "cp /vagrant/.ansible/configure/templates/mortality.service /etc/systemd/system/mortality.service"

- name: 'Run Development'
  tags:
    - 'application'
  sudo: true
  service: name=mortality state=started
